name: NSE Symbols Release

on:
  workflow_dispatch:        # Manual trigger
  schedule:
    - cron: '0 0 1 * *'     # 1st day of every month at 00:00 UTC

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: npm install

    # 4️⃣ Run NSE script
    - name: Run NSE fetch script
      run: node index.js

    # 5️⃣ Create or update latest release
    - name: Create or update latest release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: NSE Symbols Latest
        files: |
          derivatives_symbols.csv
          tradingview_symbols.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
